// <auto-generated />
using EcommerceWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230412085928_addImageUrlToProduct")]
    partial class addImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Essentials for Face"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Essentials for Eyes"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Essentials for Lips"
                        });
                });

            modelBuilder.Entity("EcommerceWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("MadeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nivea",
                            CategoryId = 1,
                            Description = "Keeps the body hydrated and it will nourish and make your body soft",
                            ImageUrl = "",
                            ListPrice = 99.0,
                            MadeIn = "India",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Shower Gel"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Dazler",
                            CategoryId = 1,
                            Description = "best thing to paint your nail which will give elegant color to ur nails.which will make u more attractive",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            MadeIn = "India",
                            Price = 80.0,
                            Price100 = 70.0,
                            Price50 = 75.0,
                            Title = "Nail Varnish"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Lakme",
                            CategoryId = 2,
                            Description = "Best product to make ur eyes more attractive",
                            ImageUrl = "",
                            ListPrice = 150.0,
                            MadeIn = "India",
                            Price = 140.0,
                            Price100 = 130.0,
                            Price50 = 135.0,
                            Title = "Eye Liner"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Mac matte",
                            CategoryId = 2,
                            Description = "Best thing which will add more colors to Lips and make u more beautiful",
                            ImageUrl = "",
                            ListPrice = 300.0,
                            MadeIn = "India",
                            Price = 250.0,
                            Price100 = 180.0,
                            Price50 = 200.0,
                            Title = "Lipstick"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Dermavive",
                            CategoryId = 3,
                            Description = "Keep your skin more soft and bright",
                            ImageUrl = "",
                            ListPrice = 800.0,
                            MadeIn = "India",
                            Price = 780.0,
                            Price100 = 700.0,
                            Price50 = 750.0,
                            Title = "Moisturizer"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Head and Shoulder",
                            CategoryId = 3,
                            Description = "Keep your hair dandruf free soft and silky",
                            ImageUrl = "",
                            ListPrice = 200.0,
                            MadeIn = "India",
                            Price = 180.0,
                            Price100 = 170.0,
                            Price50 = 175.0,
                            Title = "Shampoo"
                        });
                });

            modelBuilder.Entity("EcommerceWeb.Models.Product", b =>
                {
                    b.HasOne("EcommerceWeb.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
